src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: TeamMember::class, orphanRemoval: true)]
    private Collection $teamMembers;

    #[ORM\OneToMany(mappedBy: 'project_lead', targetEntity: Project::class)]
    private Collection $projects;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: VacationRequest::class)]
    private Collection $vacationRequests;

    #[ORM\Column]
    private ?int $days_left = null;

    public function __construct()
    {
        $this->teamMembers = new ArrayCollection();
        $this->projects = new ArrayCollection();
        $this->vacationRequests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return Collection<int, TeamMember>
     */
    public function getTeamMembers(): Collection
    {
        return $this->teamMembers;
    }

    public function addTeamMember(TeamMember $teamMember): static
    {
        if (!$this->teamMembers->contains($teamMember)) {
            $this->teamMembers->add($teamMember);
            $teamMember->setUser($this);
        }

        return $this;
    }

    public function removeTeamMember(TeamMember $teamMember): static
    {
        if ($this->teamMembers->removeElement($teamMember)) {
            // set the owning side to null (unless already changed)
            if ($teamMember->getUser() === $this) {
                $teamMember->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Project>
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): static
    {
        if (!$this->projects->contains($project)) {
            $this->projects->add($project);
            $project->setProjectLead($this);
        }

        return $this;
    }

    public function removeProject(Project $project): static
    {
        if ($this->projects->removeElement($project)) {
            // set the owning side to null (unless already changed)
            if ($project->getProjectLead() === $this) {
                $project->setProjectLead(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, VacationRequest>
     */
    public function getVacationRequests(): Collection
    {
        return $this->vacationRequests;
    }

    public function addVacationRequest(VacationRequest $vacationRequest): static
    {
        if (!$this->vacationRequests->contains($vacationRequest)) {
            $this->vacationRequests->add($vacationRequest);
            $vacationRequest->setUser($this);
        }

        return $this;
    }

    public function removeVacationRequest(VacationRequest $vacationRequest): static
    {
        if ($this->vacationRequests->removeElement($vacationRequest)) {
            // set the owning side to null (unless already changed)
            if ($vacationRequest->getUser() === $this) {
                $vacationRequest->setUser(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getDaysLeft(): ?int
    {
        return $this->days_left;
    }

    public function setDaysLeft(int $days_left): static
    {
        $this->days_left = $days_left;

        return $this;
    }
}

src/Entity/VacationRequest.php
<?php

namespace App\Entity;

use App\Repository\VacationRequestRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VacationRequestRepository::class)]
class VacationRequest
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column]
    private ?bool $project_lead_approved = null;

    #[ORM\Column]
    private ?bool $team_lead_approved = null;

    #[ORM\ManyToOne(inversedBy: 'vacationRequests')]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function isProjectLeadApproved(): ?bool
    {
        return $this->project_lead_approved;
    }

    public function setProjectLeadApproved(bool $project_lead_approved): static
    {
        $this->project_lead_approved = $project_lead_approved;

        return $this;
    }

    public function isTeamLeadApproved(): ?bool
    {
        return $this->team_lead_approved;
    }

    public function setTeamLeadApproved(bool $team_lead_approved): static
    {
        $this->team_lead_approved = $team_lead_approved;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/VacationRequestType.php
<?php

namespace App\Form;

use App\Entity\VacationRequest;
use Symfony\Component\Form\AbstractType;
use App\Validator\Constraints\WithinCurrentYear;
use Symfony\Component\Form\FormBuilderInterface;
use App\Validator\Constraints\VacationRequestLimit;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VacationRequestType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('start_date', null, [
                'constraints' => [
                    new WithinCurrentYear(),
                ],
            ])
            ->add('end_date', null, [
                'constraints' => [
                    new VacationRequestLimit(),
                    new WithinCurrentYear(),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => VacationRequest::class,
        ]);
    }
}

src/Controller/VacationRequestController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\VacationRequest;
use App\Form\VacationRequestType;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\VacationRequestRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Service\ApproverVacationRequestService;
use App\Service\VacationRequestService;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/vacation-request')]
class VacationRequestController extends AbstractController
{
    #[Route('/', name: 'app_vacation_request_index', methods: ['GET'])]
    public function index(VacationRequestRepository $vacationRequestRepository, ApproverVacationRequestService $approverVacationRequestService): Response
    {
        $user = $this->getUser();
        if (!$user instanceof User) {
            return $this->redirectToRoute('app_vacation_request_index', [], Response::HTTP_SEE_OTHER);
        }
        $roles = $user->getRoles();

        if (in_array('ROLE_ADMIN', $roles)) {
            return $this->render('vacation_request/index.html.twig', [
                'vacation_requests' => $vacationRequestRepository->findAll(),
                'user_roles' => $user->getRoles(),
            ]);
        }

        if (in_array('ROLE_TEAM_LEAD', $roles) || in_array('ROLE_PROJECT_LEAD', $roles)) {
            return $this->render('vacation_request/index.html.twig', [
                'vacation_requests' => $approverVacationRequestService->getFilteredVacationRequests($user),
                'user_name' => $user->getFirstName() . ' ' . $user->getLastName(),
                'user_roles' => $user->getRoles(),
            ]);
        }
        return $this->render('vacation_request/index.html.twig', [
            'vacation_requests' => $vacationRequestRepository->findBy(['user' => ['id' => $user->getId()]]),
            'days_left' => $user->getDaysLeft(),
            'user_roles' => $user->getRoles(),
        ]);
    }

    #[Route('/new', name: 'app_vacation_request_new', methods: ['GET', 'POST'])]
    public function new(Request $request, VacationRequestService $vacationRequestService): Response
    {
        $vacationRequest = new VacationRequest();
        $user = $this->getUser();
        if (!$user instanceof User) {
            return $this->redirectToRoute('app_vacation_request_index', [], Response::HTTP_SEE_OTHER);
        }
        $form = $this->createForm(VacationRequestType::class, $vacationRequest);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $vacationRequestService->createVacationRequest($vacationRequest, $user);
            return $this->redirectToRoute('app_vacation_request_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vacation_request/new.html.twig', [
            'vacation_request' => $vacationRequest,
            'form' => $form,
            'days_left' => $user->getDaysLeft(),
        ]);
    }

    #[Route('/{id}', name: 'app_vacation_request_show', methods: ['GET'])]
    public function show(VacationRequest $vacationRequest): Response
    {
        return $this->render('vacation_request/show.html.twig', [
            'vacation_request' => $vacationRequest,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_vacation_request_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, VacationRequest $vacationRequest, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VacationRequestType::class, $vacationRequest);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_vacation_request_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vacation_request/edit.html.twig', [
            'vacation_request' => $vacationRequest,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_vacation_request_delete', methods: ['POST'])]
    public function delete(Request $request, VacationRequest $vacationRequest, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $vacationRequest->getId(), $request->request->get('_token'))) {
            $entityManager->remove($vacationRequest);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_vacation_request_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/approve', name: 'app_vacation_request_approve', methods: ['GET'])]
    public function approve(VacationRequest $vacationRequest, ApproverVacationRequestService $approverVacationRequestService): Response
    {
        $approverVacationRequestService->approveVacationRequest($vacationRequest, $this->getUser());

        return $this->redirectToRoute('app_vacation_request_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/vacation_request/_delete_form.html.twig
<form method="post" action="{{ path('app_vacation_request_delete', {'id': vacation_request.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vacation_request.id) }}">
    <button class="btn">Delete</button>
</form>

templates/vacation_request/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/vacation_request/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit VacationRequest{% endblock %}

{% block body %}
    <h1>Edit VacationRequest</h1>

    {{ include('vacation_request/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_vacation_request_index') }}">back to list</a>

    {{ include('vacation_request/_delete_form.html.twig') }}
{% endblock %}

templates/vacation_request/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}VacationRequest index{% endblock %}

{% block body %}
    <h1>VacationRequest index</h1>
    {% if 'ROLE_EMPLOYEE' in user_roles %}
        <h2>Days left: {{ days_left }}</h2>
    {% endif %}
    
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Full name</th>
                <th>Start_date</th>
                <th>End_date</th>
                {% if 'ROLE_PROJECT_LEAD' in user_roles or 'ROLE_EMPLOYEE' in user_roles or 'ROLE_ADMIN' in user_roles %}
                    <th>Project_lead_approved</th>
                {% endif %}
                {% if 'ROLE_TEAM_LEAD' in user_roles or 'ROLE_EMPLOYEE' in user_roles or 'ROLE_ADMIN' in user_roles %}
                    <th>Team_lead_approved</th>
                {% endif %}
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for vacation_request in vacation_requests %}
            <tr>
                <td>{{ vacation_request.id }}</td>
                <td>{{ vacation_request.user.firstName }} {{ vacation_request.user.lastName }}</td>
                <td>{{ vacation_request.startDate ? vacation_request.startDate|date('Y-m-d') : '' }}</td>
                <td>{{ vacation_request.endDate ? vacation_request.endDate|date('Y-m-d') : '' }}</td>
                {% if 'ROLE_EMPLOYEE' in user_roles %}
                    <td>{{ vacation_request.projectLeadApproved ? 'Yes' : 'No' }}</td>
                    <td>{{ vacation_request.teamLeadApproved ? 'Yes' : 'No' }}</td>       
                    <td>
                        <a href="{{ path('app_vacation_request_show', {'id': vacation_request.id}) }}">show</a>
                        <a href="{{ path('app_vacation_request_edit', {'id': vacation_request.id}) }}">edit</a>
                    </td>    
                {% elseif 'ROLE_PROJECT_LEAD' in user_roles or 'ROLE_TEAM_LEAD' in user_roles %}
                    {% if 'ROLE_PROJECT_LEAD' in user_roles %}
                        <td>{{ vacation_request.projectLeadApproved ? 'Yes' : 'No' }}</td>
                    {% endif %}
                    {% if 'ROLE_TEAM_LEAD' in user_roles %}
                        <td>{{ vacation_request.teamLeadApproved ? 'Yes' : 'No' }}</td>  
                    {% endif %}
                    <td>
                        <a href="{{ path('app_vacation_request_approve', {'id': vacation_request.id}) }}">Approve</a>
                    </td>
                {% endif %}
                {% if 'ROLE_ADMIN' in user_roles %}
                    <td>{{ vacation_request.projectLeadApproved ? 'Yes' : 'No' }}</td>
                    <td>{{ vacation_request.teamLeadApproved ? 'Yes' : 'No' }}</td>
                    <td>
                        <a href="{{ path('app_vacation_request_show', {'id': vacation_request.id}) }}">show</a>
                        <a href="{{ path('app_vacation_request_edit', {'id': vacation_request.id}) }}">edit</a>
                        <a href="{{ path('app_vacation_request_approve', {'id': vacation_request.id}) }}">Approve</a>
                    </td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if 'ROLE_EMPLOYEE' in user_roles %}
        <a href="{{ path('app_vacation_request_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/vacation_request/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New VacationRequest{% endblock %}

{% block body %}
    <h1>Create new VacationRequest</h1>
    <h2>Days left: {{ days_left }}</h2>

    {{ include('vacation_request/_form.html.twig') }}

    <a href="{{ path('app_vacation_request_index') }}">back to list</a>
{% endblock %}

templates/vacation_request/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}VacationRequest{% endblock %}

{% block body %}
    <h1>VacationRequest</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vacation_request.id }}</td>
            </tr>
            <tr>
                <th>Start_date</th>
                <td>{{ vacation_request.startDate ? vacation_request.startDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End_date</th>
                <td>{{ vacation_request.endDate ? vacation_request.endDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ vacation_request.status }}</td>
            </tr>
            <tr>
                <th>Project_lead_approved</th>
                <td>{{ vacation_request.projectLeadApproved ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Team_lead_approved</th>
                <td>{{ vacation_request.teamLeadApproved ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_vacation_request_index') }}">back to list</a>

    <a href="{{ path('app_vacation_request_edit', {'id': vacation_request.id}) }}">edit</a>

    {{ include('vacation_request/_delete_form.html.twig') }}
{% endblock %}